name: linting, testing, building

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm install

      - name: Build production project
        run: npm run build:prod

      - name: Linting TypeScript
        run: npm run lint:ts

      - name: Linting CSS
        run: npm run lint:scss

      - name: Unit testing
        run: npm run test:unit
