name: Linting, Testing, Building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: install modules
        run: npm install --force

      - name: Build and Test
        run: |
          npm run build:prod &
          npm run lint:ts &
          npm run lint:scss &
          npm run test:unit &
          wait

      - name: Build Storybook
        run: npm run storybook:build

      - name: Screenshot Testing
        run: npm run test:ui:ci
