name: linting, testing, building

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Starting Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install modules
        run: npm install --force

      - name: Linting TypeScript
        run: npm run lint:ts

      - name: Linting CSS
        run: npm run lint:scss

              - name: Unit Testing
        run: npm run test:unit

  building:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Starting Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install modules
        run: npm install --force

      - name: Build production project
        run: npm run build:prod

      - name: Build Storybook
        run: npm run storybook:build

      - name: Screenshot Testing
        run: npm run test:ui:ci

  pipeline:
    needs: [linting, testing, building]
    runs-on: windows-2019
    steps:
      - name: Check results
        run: echo "Linting, testing, and building jobs are complete."