name: linting, testing, building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [18.x]

    lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install modules
        run: npm install --force
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unit testing
        run: npm run test:unit
    build and screen-test:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
          - name: build production project
        run: npm run build:prod
        - name: build storybook
        run: npm run storybook:build
      - name: screenshot testing
        run: npm run test:ui:ci

