name: linting, testing, building

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm install --force

  linting:
    needs: pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Linting TypeScript
        run: npm run lint:ts

      - name: Linting CSS
        run: npm run lint:scss

  testing:
    needs: pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Unit testing
        run: npm run test:unit

      - name: Build Storybook
        run: npm run storybook:build

      - name: Screenshot testing
        run: npm run test:ui:ci

  building:
    needs: pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Build production project
        run: npm run build:prod
