name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm install --force

      - name: Lint TypeScript
        run: npm run lint:ts

      - name: Lint CSS
        run: npm run lint:scss

     - name: Run unit tests
        run: npm run test:unit

  testing:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm install --force

      - name: Build Storybook
        run: npm run storybook:build

      - name: Run UI tests
        run: npm run test:ui:ci

  building:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm install --force

      - name: Build production project
        run: npm run build:prod

