on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm install --force

      - name: Run linting
        id: linting
        run: npm run lint:ts && npm run lint:scss

      - name: Run testing
        id: testing
        run: npm run test:unit

      - name: Run building
        id: building
        run: |
          npm run build:prod
          npm run storybook:build
          npm run test:ui:ci
        needs: [linting, testing]
