on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm install --force

      - name: Run linting and testing
        needs: [linting, testing]

      - name: Build production project
        run: npm run build:prod
        if: always()

      - name: Build Storybook
        run: npm run storybook:build

      - name: Run screenshot testing
        run: npm run test:ui:ci

  linting:
    runs-on: windows-2019

    steps:
      - name: Linting TypeScript
        run: npm run lint:ts
        if: always()

      - name: Linting CSS
        run: npm run lint:scss
        if: always()

  testing:
    runs-on: windows-2019

    steps:
      - name: Unit Testing
        run: npm run test:unit
        if: always()
